[build]
dockerfile = "Dockerfile"

[deploy]
startCommand = "sh start.sh"

[environment]
DATABASE_URL = "$DATABASE_URL"
POSTGRES_PASSWORD = "$POSTGRES_PASSWORD"
SECRET_KEY = "$SECRET_KEY"
UPLOAD_FOLDER = "/app/static/uploads"
