name: Debug Python

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          
      - run: python --version
      - run: pip --version
      - run: pip install -r requirements.txt
      - run: python -c "import sys; print(sys.path)"
